// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// NaturalSplineC
NumericMatrix NaturalSplineC(NumericVector& x);
RcppExport SEXP _GAM2_NaturalSplineC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(NaturalSplineC(x));
    return rcpp_result_gen;
END_RCPP
}
// calCoefDiffC
double calCoefDiffC(int p, NumericMatrix& X, NumericVector& y, double alpha_hat, NumericMatrix& f_hat, NumericVector& lambda, List& Coef, List& Coef_old, double Coef_diff);
RcppExport SEXP _GAM2_calCoefDiffC(SEXP pSEXP, SEXP XSEXP, SEXP ySEXP, SEXP alpha_hatSEXP, SEXP f_hatSEXP, SEXP lambdaSEXP, SEXP CoefSEXP, SEXP Coef_oldSEXP, SEXP Coef_diffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type alpha_hat(alpha_hatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type f_hat(f_hatSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< List& >::type Coef(CoefSEXP);
    Rcpp::traits::input_parameter< List& >::type Coef_old(Coef_oldSEXP);
    Rcpp::traits::input_parameter< double >::type Coef_diff(Coef_diffSEXP);
    rcpp_result_gen = Rcpp::wrap(calCoefDiffC(p, X, y, alpha_hat, f_hat, lambda, Coef, Coef_old, Coef_diff));
    return rcpp_result_gen;
END_RCPP
}
// KernelMatrixC
NumericMatrix KernelMatrixC(NumericVector& x);
RcppExport SEXP _GAM2_KernelMatrixC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(KernelMatrixC(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GAM2_NaturalSplineC", (DL_FUNC) &_GAM2_NaturalSplineC, 1},
    {"_GAM2_calCoefDiffC", (DL_FUNC) &_GAM2_calCoefDiffC, 9},
    {"_GAM2_KernelMatrixC", (DL_FUNC) &_GAM2_KernelMatrixC, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_GAM2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
