# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Natural spline method
#' @param x: Attribute vector
#' @param knots: Vector of knots (default: all unique values of x)
#' @return: Natural Spline matrix N, each column represents a basis function, each row corresponds to a value of x
#' @export
NaturalSplineC <- function(x) {
    .Call('_GAM2_NaturalSplineC', PACKAGE = 'GAM2', x)
}

calCoefDiffC <- function(p, X, y, alpha_hat, f_hat, lambda, Coef, Coef_old, Coef_diff) {
    .Call('_GAM2_calCoefDiffC', PACKAGE = 'GAM2', p, X, y, alpha_hat, f_hat, lambda, Coef, Coef_old, Coef_diff)
}

#' kernel matrix method
#' @param x: Attribute vector
#' @return: Kernel Matrix K
#' @export
KernelMatrixC <- function(x) {
    .Call('_GAM2_KernelMatrixC', PACKAGE = 'GAM2', x)
}

